### ISSUE TITLE
Out of date documentation

### ISSUE THREAD

**Issue by lazear** [molstar/docs#15]
Hi, 

I'm trying to use MolStar as a react component following the documentation (https://molstar.org/docs/plugin/#plugincontext-with-built-in-react-ui), but getting some errors (`createPluginAsync` is gone, `createPluginUI` has a different type signature now) that I assume are from the most recent 4.0 release.

Are there up-to-date docs for integrating 4.0 with react? Thank you for the continued support of MolStar - it's a fantastic piece of software.

**Comment by dsehnal** [comment]
I've pushed an update.
