### ISSUE TITLE
Creating Plugin Instance example usage without using WebPack has incorrect syntax

### ISSUE THREAD

**Issue by ArnNag** [molstar/docs#9]
In the code for "Example usage without using WebPack" at https://molstar.org/docs/plugin/, the viewer is initialized as
`  var viewer = new molstar.Viewer('app', {
        layoutIsExpanded: false,
        layoutShowControls: false,
        layoutShowRemoteState: false,
        layoutShowSequence: true,
        layoutShowLog: false,
        layoutShowLeftPanel: true,
        viewportShowExpand: true,
        viewportShowSelectionMode: false,
        viewportShowAnimation: false,
        pdbProvider: 'rcsb',
        emdbProvider: 'rcsb',
    });`
This results in an error since it does not follow the constructor syntax in Viewer. It should be updated to match https://github.com/molstar/molstar/blob/7094f8f2651dfb0c83baec98ff9c1d2cf0468c87/src/apps/viewer/embedded.html .

**Comment by dsehnal** [comment]
Should be fixed, thanks.
